# Generated by Django 5.1.15 on 2026-07-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newsindexpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspage',
            options={'ordering': ['-first_published_at'], 'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
    ]
